# Generated by Django 4.0.6 on 2026-03-07 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('is_use', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(help_text='eg, xxx.data.storemesh.com', max_length=300)),
                ('path_prefix', models.CharField(default='/', help_text="path prefix eg, /static',/media/ or / ", max_length=100)),
                ('pass_host_header', models.BooleanField(default=True)),
                ('url', models.URLField(help_text='url for route to, eg http://192.168.24.206:8000')),
                ('is_use', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.project')),
            ],
        ),
    ]
