version: '3'
networks:
    traefik:
        external:
            name: traefik

services:
    # proxy:
    #     image: traefik:1.7-alpine # The official Traefik docker image
    #     command: --docker
    #     restart: always
    #     networks:
    #         - traefik
    #     ports:
    #         - "80:80"
    #         - "443:443"
    #     volumes:
    #         -  "./traefik.toml:/traefik.toml"
    #         -  "./acme.json:/acme.json"
    #         -  "./config-rules:/config-rules"
    #         - /var/run/docker.sock:/var/run/docker.sock
    #     labels:
    #         - "traefik.frontend.rule=Host:traefik.data.storemesh.com"
    #         - "traefik.port=8080"
    #         - "traefik.backend=traefik"
    #         - "traefik.frontend.entryPoints=http,https"

    db:
        container_name: ${PROJECT_NAME}-db
        image: postgres:11.3-alpine
        env_file:
            - .env

    backend:
        container_name: ${PROJECT_NAME}-backend
        build: ./backend
        command: sh runserver.sh
        volumes: 
            - ./backend:/backend
            - "./config-rules:/config-rules"
        ports: 
            - 8000:8000
        env_file: 
            - .env