# traefik.toml
################################################################
# Global configuration
################################################################

# defaultEntryPoints must be at the top because it should not be in any table below
defaultEntryPoints = ["http", "https"]

# Entrypoints, http and https
[entryPoints]

# http should be redirected to https
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.forwardedHeaders]
      insecure = true
    [entryPoints.http.redirect]
      entryPoint = "https"

# https is the default
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.forwardedHeaders]
      insecure = true
    [entryPoints.https.tls]

[web]
# Port for the status page
address = ":8080"

# Enable Basic authentication in an entry point
# Passwords are encoded in MD5: you can use htpasswd to generate them.
[web.auth.basic]
  users = ["admin:$apr1$Vgma/TnS$OpA8l1Gkm3GB9Q/tTY9Bt1"]

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
# caServer = "https://acme-staging.api.letsencrypt.org/directory"
email = "mail@data.storemesh.com"
storage = "acme.json" # or "traefik/acme/account" if using KV store
entryPoint = "https"
onDemand = false
OnHostRule = true

[acme.httpChallenge]
  entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "data.storemesh.com"
watch = true
exposedbydefault = false

[file]
  directory = "/config_rule/"
  watch = true